# Generated by Django 4.2.4 on 2023-08-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_long_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='long_description',
            new_name='description_long',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='short_description',
            new_name='description_short',
        ),
    ]
